@startuml
'https://plantuml.com/sequence-diagram
'Author: Hossam Elwahsh
!theme cerulean
title Login Sequence Diagram
autonumber
actor User

== Sample Registration ==
User -> Front_End: Register
activate Front_End
activate User
deactivate User
Front_End -> Back_End: User Data
activate Back_End
Back_End -> Back_End: set login_trials = 0
Back_End --> Front_End: alert "Registration success"
deactivate Back_End
deactivate Front_End

User -> Front_End: Navigate to login
activate Front_End
activate User
deactivate Front_End
deactivate User

== Login ==
User -> Front_End: Enter email
activate Front_End #lightblue
activate User
deactivate Front_End
deactivate User
User -> Front_End: Enter password
activate Front_End #lightblue
deactivate Front_End
activate User
deactivate User

User -> Front_End: Login Request
activate Front_End #lightblue
Front_End -> Front_End: basic validation\nemail, password syntax

alt #mistyrose invalid input
    Front_End -[#indianred]-> Front_End: **alert** "Invalid Input"

else #technology valid input
    Front_End -> Back_End: send user login info

    deactivate Front_End #lightblue
    activate Back_End #darkSalmon
end

alt #mistyrose user email doesn't exist

Back_End -[#indianred]-> Front_End: **alert** "Invalid email address\nUser not found"
activate Front_End #lightblue
deactivate Front_End

else #white user email exist
    alt #pink user account is locked
    Back_End -[#indianred]-> Front_End: **alert** "Your account is locked/disabled."
    activate Front_End #lightblue
    deactivate Front_End

    else #white user account is OK
        alt #mistyrose wrong password
        Back_End -> Back_End: **login_trials++**

            alt #pink login_trials >= 3
                Back_End -> Back_End: **Lock User Account**
                Back_End --> Front_End: **alert** "3 failed login attempts\nyour account has been locked"
                activate Front_End #lightblue
                deactivate Front_End

            else #mistyrose login_trials < 3
            Back_End --> Front_End: **alert** "failed login attempt <login_trials>/3"
            activate Front_End #lightblue
            deactivate Front_End

            end

        else #technology password OK
            Back_End -> Back_End: set **login_trials = 0**
            Back_End --> Front_End: Login success
            activate Front_End #lightblue
            Front_End --> Front_End: redirect to welcome page
            deactivate Front_End
        end
    end

end

@enduml
